# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-11 04:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('urls', '0002_auto_20170311_0414'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrlAnalitys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('browser', models.CharField(max_length=255)),
                ('ip', models.CharField(max_length=20)),
                ('lang', models.CharField(max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='urls.Url')),
            ],
        ),
    ]
