# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-11 04:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urls', '0004_auto_20170311_0420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urlanalitys',
            name='lang',
        ),
    ]
