# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-11 04:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('urls', '0006_auto_20170311_0442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlanalitys',
            name='url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analitys', to='urls.Url'),
        ),
    ]
